/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.GUI;

import client.DTO.Hotel;
import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author TTC
 */
public class ItemHotelInCT extends javax.swing.JPanel {

    /**
     * Creates new form ItemHotelInCT
     */
    public ItemHotelInCT() {
        initComponents();
    }

    ItemHotelInCT(Hotel e) {
        initComponents();
        
        
        this.name.setText(e.getName());
        
        this.price.setText(e.getPrice());
        
        this.location.setText(e.getLocaltion());
        
        this.rated.setText(e.getRated());
        
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rated = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        price = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setText("name");

        location.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/img/icons8_google_maps_16.png"))); // NOI18N
        location.setText("location");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rated.setText("rated");
        jPanel1.add(rated, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img.setText("img");
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 208, 120));

        price.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        price.setText("price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(location, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                    .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(location)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JLabel location;
    private javax.swing.JLabel name;
    private javax.swing.JLabel price;
    private javax.swing.JLabel rated;
    // End of variables declaration//GEN-END:variables
}
