/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author TTC
 */
public class MainFarme extends javax.swing.JFrame {

    /**
     * Creates new form MainFarme
     */
    public MainFarme() throws IOException {
        initComponents();

        //        this.setExtendedState(this.MAXIMIZED_BOTH); 
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize);

        this.setTitle("Đề tài 15 : Tra cứu thông tin địa lý");

        String currentPath = new java.io.File(".").getCanonicalPath();
        String urlIcon = currentPath + "\\src\\client\\img\\img-icon.PNG";
        ImageIcon imgIcon = new ImageIcon(urlIcon);
        this.setIconImage(imgIcon.getImage());
        System.out.println(this.getWidth());

        wrap.setSize(this.getSize());
        container.setSize(this.getWidth() - 2 * spaceLeft.getWidth(), this.getHeight());
//        jScrollPane2.setSize(container.getSize());
        jScrollPane2.setSize(container.getSize());

        jPanel1.setSize(container.getSize());
        jPanel3.setSize(container.getWidth(), container.getHeight() / 2);
        jPanel2.setSize(container.getWidth(), container.getHeight() / 2);


        System.out.println(jPanel3.getSize());
        System.out.println(this.getSize());
        System.out.println(jPanel1.getSize());
        System.out.println(container.getSize());
        this.repaint();

//        jScrollPane2.setSize(container.getSize());
//        jScrollPane2.setPreferredSize(container.getSize());
//        jPanel1.setPreferredSize(container.getSize());
//        jPanel3.setSize(container.getWidth(),container.getHeight()/2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrap = new javax.swing.JPanel();
        spaceLeft = new javax.swing.JPanel();
        spaceRight = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(this.MAXIMIZED_BOTH);
        getContentPane().setLayout(null);

        wrap.setBackground(new java.awt.Color(102, 204, 0));
        wrap.setPreferredSize(null);
        wrap.setLayout(new java.awt.BorderLayout());

        spaceLeft.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout spaceLeftLayout = new javax.swing.GroupLayout(spaceLeft);
        spaceLeft.setLayout(spaceLeftLayout);
        spaceLeftLayout.setHorizontalGroup(
            spaceLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        spaceLeftLayout.setVerticalGroup(
            spaceLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        wrap.add(spaceLeft, java.awt.BorderLayout.LINE_START);

        spaceRight.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout spaceRightLayout = new javax.swing.GroupLayout(spaceRight);
        spaceRight.setLayout(spaceRightLayout);
        spaceRightLayout.setHorizontalGroup(
            spaceRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        spaceRightLayout.setVerticalGroup(
            spaceRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        wrap.add(spaceRight, java.awt.BorderLayout.LINE_END);

        jScrollPane2.setBackground(new java.awt.Color(102, 255, 0));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(432, 408));

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        wrap.add(container, java.awt.BorderLayout.CENTER);

        getContentPane().add(wrap);
        wrap.setBounds(0, 0, 370, 320);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFarme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFarme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFarme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFarme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFarme().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainFarme.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel container;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JPanel spaceLeft;
    public javax.swing.JPanel spaceRight;
    public static javax.swing.JPanel wrap;
    // End of variables declaration//GEN-END:variables
}
