/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.GUI;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author TTC
 */
public class searchPanel extends javax.swing.JPanel {

    /**
     * Creates new form searchPanel
     */
    public searchPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/img/icons8_search_32.png"))); // NOI18N

        setLayout(null);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/img/icons8_search_16.png"))); // NOI18N
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                handleClickBtnSearch(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch);
        btnSearch.setBounds(360, 0, 40, 30);

        searchField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchField.setToolTipText("");
        searchField.setAlignmentX(5.0F);
        searchField.setAlignmentY(1.0F);
        searchField.setAutoscrolls(false);
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchFieldKeyPressed(evt);
            }
        });
        add(searchField);
        searchField.setBounds(0, 0, 360, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnSearch.doClick();
        }
 
    }//GEN-LAST:event_searchFieldKeyPressed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String value = searchField.getText().trim();
        if (value.length()>0) {
            try {
                client.Client.ctrl.sendMessage(client.Client.ctrl.SEND_SEARCH+client.ClientController.SPLIT_TWO+value);
            } catch (IOException ex) {
                Logger.getLogger(searchPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void handleClickBtnSearch(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handleClickBtnSearch
    }//GEN-LAST:event_handleClickBtnSearch


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
