/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.GUI;

import client.Client;
import client.DTO.Country;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;

import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author TTC
 */
public class SearchCountryItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchCountryItemPanel
     */
    private Country country;

    public SearchCountryItemPanel(Country country) throws MalformedURLException, IOException {
        this.country = country;
        initComponents();
        this.countryName.setBackground(Color.yellow);
        Dimension d = new Dimension(1150, 50);
        this.setMaximumSize(d);
        this.setMinimumSize(d);
        this.setBackground(Color.white);
        Image image = null;
        URL url = new URL(this.country.getUrl());
        image = ImageIO.read(url);
        image = getScaledImage(image, 60, 40);
        ImageIcon icon = new ImageIcon(image);

        this.flag.setIcon(icon);
        this.flag.setBounds(0, 0, 60, 40);

        this.countryName.setText(country.getName());
        this.countryName.setBounds(65, 0, 1085, 40);

        this.repaint();
    }

    public Image getScaledImage(Image Img, int wt, int ht) {
        BufferedImage resizedImg = new BufferedImage(wt, ht, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = resizedImg.createGraphics();

        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(Img, 0, 0, wt, ht, null);
        g2.dispose();

        return resizedImg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flag = new javax.swing.JLabel();
        countryName = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                handleClick(evt);
            }
        });
        setLayout(null);

        flag.setText("img");
        add(flag);
        flag.setBounds(0, 0, 80, 50);

        countryName.setBackground(new java.awt.Color(255, 255, 51));
        countryName.setText("name");
        add(countryName);
        countryName.setBounds(83, -1, 660, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void handleClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handleClick
        System.out.println(this.country.toString());
        try {
            Client.countryActive=this.country;
            client.Client.countryPanel =new CountryPanel(this.country,client.Client.dms);
        } catch (IOException ex) {
            Logger.getLogger(SearchCountryItemPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        client.Client.countryPanel.setBounds(100, 55, Client.farme.getWidth() - 200, 600);
        
        Client.farme.container.removeAll();
        Client.farme.container.add(Client.countryPanel);
        
        Client.farme.container.repaint();
        Client.farme.validate();
        Client.farme.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_handleClick


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel countryName;
    public javax.swing.JLabel flag;
    // End of variables declaration//GEN-END:variables
}
