/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.GUI;

import java.awt.Dimension;

/**
 *
 * @author TTC
 */
public class TitleFarme extends javax.swing.JPanel {

    /**
     * Creates new form TitleFarme
     */
    public TitleFarme(String title,Dimension dms) {
        initComponents();
        this.setMinimumSize(dms);
        this.setMaximumSize(dms);
        this.lableName.setText("   "+title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lableName = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        lableName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lableName.setText("jLabel1");
        add(lableName);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lableName;
    // End of variables declaration//GEN-END:variables
}
